pool: Default

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Install
        steps:
          - script: |
              echo "Hello"
              npm install
              npm run build
              npm test
          - publish: dist
            artifact: dist
  - stage: DeployDev
    displayName: Deploy to dev
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              find .