pool: Default

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Install
        steps:
          - script: |
              npm i -g @baseplate-sdk/cli
          - script: |
              npm install
              npm run build
              npm test
          - publish: dist
            artifact: dist

  - stage: Deploy0
    displayName: Deploy to dev
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment dev --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)

  - stage: Deploy1
    displayName: Deploy to stage
    dependsOn: Deploy0
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment stage --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)

  - stage: Deploy2
    displayName: Deploy to test
    dependsOn: Deploy1
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment test --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)

  - stage: Deploy3
    displayName: Deploy to prod
    dependsOn: Deploy2
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment prod --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)
