pool: Default

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Install
        steps:
          - publish: dist
            artifact: dist
            seal: true
            script: |
              echo "Hello"
              npm install
              npm run build
              npm test