pool: Default

trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Install
        steps:
          - script: |
              npm i -g @baseplate-sdk/cli
          - script: |
              npm install
              npm run build
              npm test
          - publish: dist
            artifact: dist
  - stage: DeployDev
    displayName: Deploy to dev
    dependsOn: Build
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment dev --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)
  - stage: DeployStage
    displayName: Deploy to stage
    dependsOn: DeployDev
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: dist
          - script: |
              baseplate deploy test --environment stage --dir ../dist --entry joel-test.js --autoVersion
            env:
              BASEPLATE_TOKEN: $(BASEPLATE_TOKEN)