trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build and test
    jobs:
      - job: Install
        steps:
          - script: |
              npm install
              npm run build
              npm test